### ISSUE TITLE
Generic provider with target url

### ISSUE THREAD

**Issue by puzich** [qdm12/ddns-updater#293] opened 2022-01-21 15:13 UTC
1. What's the feature?
Update for generic DNS Updater. In my imagination, that you can enter a url in the config which is filled with the necessary parameters. For example:

https://dyndns-updater.com/dyn.php?user=<user>&password=<password>&ip=<ip>

or something like that, so that anyone can maybe use his selfhosted dyndns server .

2. Extra information?

**Comment by qdm12** [comment] 2024-01-19 11:09
I'm thinking of a new provider with the json settings:

```json
{
  "url": "https://dyndns-updater.com/dyn.php](https://dyndns-updater.com/dyn.php?user=a&password=b",
  "ipv4key": "myip4",
  "ipv6key": "myip6",
}
```

The `url` contains everything (user/password/token/etc.) that is static, the `ipv4key`/`ipv6key` are the url query parameter keys to use for the ipv4/ipv6 addresses. For example `&myip4=1.2.3.4`.

What do you think? Any extra fields or problems with this format?

**Comment by qdm12** [comment] 2024-01-19 19:59
Done in 0c561d437816022383a89076850e10642ca142a9

Documentation is at https://github.com/qdm12/ddns-updater/blob/master/docs/custom.md

Note this issue is a duplicate of original issue #168 so please continue the conversation on the original issue if you want to.

**Closed by qdm12** 2024-01-19 19:59 UTC
Labels: Status: 🔒 After next release, Complexity: 🟩 Easy to do, Category: New provider 🆕, Category: Good idea 🎯
