### ISSUE TITLE
Add easyDNS and ZoneEdit which use the same method?

### ISSUE THREAD

**Issue by Zogg44** [qdm12/ddns-updater#459] opened 2023-04-19 23:22 UTC
1. What's the feature?

add support for easyDNS and ZoneEdit, which are owned by the same company and use the same method but different provide URL

See https://kb.easydns.com/knowledge/dynamic-dns/ for details on easyDNS. 

For ZoneEdit, replace api.cp.easydns.com with api.cp.zoneedit.com

2. Extra information?

**Comment by jaj75074** [comment] 2023-04-21 16:26
I found some instructions on how to do this, so I wrote my own bash script. Here it is for anyone who may want it. I'm sure it could be streamlined, but it works. It gets the WAN IP, saves it to a file, reads the value back from the file, and puts it in the URL along with username and token from ZoneEdit:

wget -q -O /mnt/user/Fileshare/ddns.txt "https://icanhazip.com"

IP=`awk '{print $1}' < /mnt/user/Fileshare/ddns.txt`
echo my IP is "$IP"

wget -O/dev/null "https://MYLOGIN:MYTOKEN@api.cp.zoneedit.com/dyn/generic.php?hostname=MYHOSTNAME&myip=$IP"

**Comment by qdm12** [comment] 2023-06-05 06:47
Duplicate of #421 and #311

**Closed by qdm12** 2023-06-05 06:47 UTC
Labels: :bulb: feature request

**Comment by qdm12** [comment] 2023-06-12 14:37
EasyDNS added in 6a9ba7ecb42c94ff0cdc4051139997b34b1db672 for the latest image and future release image tag `:v2.6.0`
