### ISSUE TITLE
Ionos provider integration is broken

### ISSUE THREAD

**Issue by disi33** [qdm12/ddns-updater#758] opened 2024-07-04 14:20 UTC
Ionos integration stopped working for me, an error is thrown during initialization:

`goroutine 7 [running]:
github.com/qdm12/ddns-updater/internal/provider/providers/ionos.New({0xc0000da000, 0x11b, 0x120}, {0xc000028570, 0x11}, {0xef9f60, 0x1}, 0x1, {{{0x0, 0x0}, ...}, ...})
        github.com/qdm12/ddns-updater/internal/provider/providers/ionos/provider.go:35 +0xce
github.com/qdm12/ddns-updater/internal/provider.New({0xc0000135a8?, 0x7d38de?}, {0xc0000da000?, 0xc0000b0630?, 0xc00038f450?}, {0xc000028570?, 0xc0000b0630?}, {0xef9f60?, 0x4171da?}, 0x1, ...)
        github.com/qdm12/ddns-updater/internal/provider/provider.go:138 +0x6f8
github.com/qdm12/ddns-updater/internal/params.makeSettingsFromObject({{0xc0000135a8, 0x5}, {0xc000028570, 0x11}, {0x0, 0x0}, {0xef9f60, 0x1}, {0xc0000135b0, 0x4}, ...}, ...)
        github.com/qdm12/ddns-updater/internal/params/json.go:203 +0x61f
github.com/qdm12/ddns-updater/internal/params.extractAllSettings({0xc0000d0200, 0x138, 0x200})
        github.com/qdm12/ddns-updater/internal/params/json.go:134 +0x4d3
github.com/qdm12/ddns-updater/internal/params.(*Reader).getProvidersFromFile(0xc00038fd88, {0xc00002c070, 0x19})
        github.com/qdm12/ddns-updater/internal/params/json.go:71 +0x22d
github.com/qdm12/ddns-updater/internal/params.(*Reader).JSONProviders(0xc00038fd88, {0xc00002c070, 0x19})
        github.com/qdm12/ddns-updater/internal/params/json.go:44 +0x4e
main._main({0xbae200, 0xc0000a2050}, 0xc0002b9560, {0xc000116040?, 0x1?, 0x1?}, {0xbb49c8, 0xc0002e3d60}, {{0xba6f94, 0x6}, ...}, ...)
        ./main.go:149 +0x850
main.main.func2()
        ./main.go:65 +0x75
created by main.main in goroutine 1
        ./main.go:64 +0x2d6
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x879e8e]

goroutine 9 [running]:
github.com/qdm12/ddns-updater/internal/provider/providers/ionos.New({0xc0002bc000, 0x102, 0x120}, {0xc000029ae8, 0x11}, {0xef9f60, 0x1}, 0x1, {{{0x0, 0x0}, ...}, ...})
        github.com/qdm12/ddns-updater/internal/provider/providers/ionos/provider.go:35 +0xce
github.com/qdm12/ddns-updater/internal/provider.New({0xc0002b8238?, 0x7d38de?}, {0xc0002bc000?, 0xc00024e900?, 0xc00030f450?}, {0xc000029ae8?, 0xc00024e900?}, {0xef9f60?, 0x4171da?}, 0x1, ...)
        github.com/qdm12/ddns-updater/internal/provider/provider.go:138 +0x6f8
github.com/qdm12/ddns-updater/internal/params.makeSettingsFromObject({{0xc0002b8238, 0x5}, {0xc000029ae8, 0x11}, {0x0, 0x0}, {0xef9f60, 0x1}, {0xc0002b8240, 0x4}, ...}, ...)
        github.com/qdm12/ddns-updater/internal/params/json.go:203 +0x61f
github.com/qdm12/ddns-updater/internal/params.extractAllSettings({0xc000152800, 0x11f, 0x200})
        github.com/qdm12/ddns-updater/internal/params/json.go:134 +0x4d3
github.com/qdm12/ddns-updater/internal/params.(*Reader).getProvidersFromFile(0xc00030fd88, {0xc00002c070, 0x19})
        github.com/qdm12/ddns-updater/internal/params/json.go:71 +0x22d
github.com/qdm12/ddns-updater/internal/params.(*Reader).JSONProviders(0xc00030fd88, {0xc00002c070, 0x19})
        github.com/qdm12/ddns-updater/internal/params/json.go:44 +0x4e
main._main({0xbae200, 0xc00024c5a0}, 0xc00021d5c0, {0xc000022090?, 0x1?, 0x1?}, {0xbb49c8, 0xc000247e00}, {{0xba6f94, 0x6}, ...}, ...)
        ./main.go:149 +0x850
main.main.func2()
        ./main.go:65 +0x75
created by main.main in goroutine 1
        ./main.go:64 +0x2d6`

The configuration in the json.config file did work previously and was unchanged since. The configuration is a copy&paste of the example in the ddns-updater docs for Ionos integration with just the appropriate values updated.

**Comment by qdm12** [comment] 2024-07-04 14:23
This is a duplicate of #756 which was fixed yesterday I think 😜 Thanks for reporting this nonetheless!

**Closed by qdm12** 2024-07-04 14:23 UTC

**Comment by disi33** [comment] 2024-07-04 14:27
Thanks for the quick reply and sorry about the duplicate report! I did look at recent issues before creating this bust somehow must have missed it :D
