### ISSUE TITLE
Feature request: Additional provider do.de (Domain Offensive)

### ISSUE THREAD

**Issue by benediktheyer** [qdm12/ddns-updater#419] opened 2023-01-19 12:05 UTC
1. What's the feature?
It would be really cool if the provider do.de (Domain Offensive) was implemented.

2. Information provided for fritz-box:
* Update-URL: https://ddns.do.de/?myip=<ipaddr>
* domainname, e.g. subdomain or @
* username
* password

**Comment by qdm12** [comment] 2023-06-12 15:19
Duplicate of #310 please subscribe to that one instead (pasted your content over there)

**Closed by qdm12** 2023-06-12 15:19 UTC
Labels: New provider
