### ISSUE TITLE
Feature request: add IONOS DDNS

### ISSUE THREAD

**Issue by SHemeier** [qdm12/ddns-updater#422] opened 2023-01-24 15:31 UTC
1. What's the feature?

Add support for IONOS DDNS

2. Extra information?

Hi, 

would it be possible to add IONOS DDNS? 

https://developer.hosting.ionos.de/docs/dns

Example of the update URL: curl -X GET https://ipv4.api.hosting.ionos.com/dns/v1/dyndns?q=API_KEY
This is to update with the IP adress from where it is called, I tested this and it worked for me.

It states that it is also possible to update IPV6, but due to lack of IPV6 at home I can not try it....
However, according to their documentation it can be done via:
curl -X GET https://ipv4.api.hosting.ionos.com/dns/v1/dyndns?q=API_KEY&ipv4=<ipaddr>&ipv6=<ip6addr>
I tried it with just &ipv4=<ipaddr>, but that did not work.
It is documented here, unfortunately only in german: https://www.ionos.de/hilfe/domains/ip-adresse-konfigurieren/dynamisches-dns-ddns-einrichten-bei-company-name/

Thank you very much!

**Comment by qdm12** [comment] 2023-06-12 10:49
Duplicate of #194 please subscribe to that one instead.

**Closed by qdm12** 2023-06-12 10:49 UTC
Labels: 👥 Duplicate
