### ISSUE TITLE
Feature request: Add a DDNS server provider

### ISSUE THREAD

**Issue by xing3389** [qdm12/ddns-updater#804] opened 2024-09-06 02:49 UTC
1. What's the feature?
Add a free and easy-to-use DDNS server provider

2. Extra information?
https://www.cloudns.net/

Thank you so much

**Comment by qdm12** [comment] 2024-09-06 06:53
Duplicate of #455 please subscribe to that one instead, thanks!

**Closed by qdm12** 2024-09-06 06:53 UTC
Labels: Closed: 👥 Duplicate
