### ISSUE TITLE
Feature request: Ability to add custom providers.

### ISSUE THREAD

**Issue by upuldi** [qdm12/ddns-updater#332] opened 2022-05-05 16:10 UTC
I think it is better if there is a feature to add any custom provider.

**Comment by TimApplepie** [comment] 2022-05-23 07:12
+1

**Comment by qdm12** [comment] 2022-05-26 14:53
What do you mean? There is also the custom provider (see the wiki) where you can specify a custom openvpn config file or custom wireguard variables.

Otherwise, I'm working on simplifying the code to add more providers, but that will still require pull requests written in Go.

**Comment by Simon99de** [comment] 2022-09-26 18:06
> What do you mean? There is also the custom provider (see the wiki) where you can specify a custom openvpn config file or custom wireguard variables.
> 
> Otherwise, I'm working on simplifying the code to add more providers, but that will still require pull requests written in Go.

there are hosters, where you update the page with a url eg:
https://hoster?.de/store/dyndns/?ipaddr=<ipaddr>,&domain=my.domain.de&wildcard=0

**Comment by TCB13** [comment] 2023-07-14 17:16
+1 this is what OpenWRT and DD-WRT, do. They allow you to specify custom provider by URL.

**Comment by stalsma** [comment] 2023-11-20 15:32
Want to chime in here.  This is how Synology NAS and FritzBox routers also tackle the issue.  I am needing integrations for 2 providers that aren't listed.  

It seems like blunt-force (or regex?) substitution strategy of some sort would be trivial, and would probably eliminate a lot of the existing providers that accept an update via a get request.  Essentially define a bunch or tokens you're willing to search for and replace in a tokenized url.
![image](https://github.com/qdm12/ddns-updater/assets/5501817/c8acbbf8-69e8-448f-846a-87d9e19d9221)

**Comment by qdm12** [comment] 2024-01-19 19:59
Done in 0c561d437816022383a89076850e10642ca142a9

Documentation is at https://github.com/qdm12/ddns-updater/blob/master/docs/custom.md

Note this issue is a duplicate of original issue #168 so please continue the conversation on the original issue if you want to.

**Closed by qdm12** 2024-01-19 19:59 UTC

**Comment by TCB13** [comment] 2024-01-19 21:03
Thank you for this.
