### ISSUE TITLE
IONOS DNS API

### ISSUE THREAD

**Issue by krannich** [qdm12/ddns-updater#360] opened 2022-09-05 13:20 UTC
1. What's the feature?

Can you please add IONOS DNS API

2. Extra information?3. 

Documentation:
https://developer.hosting.ionos.de/docs/dns

**Comment by qdm12** [comment] 2022-09-06 12:37
Duplicate of #194 please subscribe to that one instead.

**Closed by qdm12** 2022-09-06 12:37 UTC
Labels: :bulb: feature request
