### ISSUE TITLE
`ipv64.net`

### ISSUE THREAD

**Issue by DAIK0N** [qdm12/ddns-updater#555] opened 2023-11-03 17:00 UTC
https://ipv64.net/dyndns_updater_api

**Comment by DAIK0N** [comment] 2023-11-03 17:02
Info to the API:
https://ipv64.net/dyndns_updater_api

**Comment by DerNordzwerg** [comment] 2023-11-10 23:25
I'd also be interested in this DNS provider.

**Comment by qdm12** [comment] 2024-06-17 20:19
Duplicate of #511 please subscribe to that one instead! Thanks!

**Closed by qdm12** 2024-06-17 20:19 UTC
Labels: Closed: 👥 Duplicate, Category: New provider 🆕
