### ISSUE TITLE
update policy should also be set to "ipv4 and ipv6" additionaly to "ipv4 or ipv6"

### ISSUE THREAD

**Issue by GUNT0815** [qdm12/ddns-updater#690] opened 2024-04-16 13:57 UTC
1. What's the feature?

Depending on your setup and ISP you might want to update your ipv4 AND ipv6 adress e.g. within your domain provider like strato in my case. 

So the request is that the config allows also

"ip_version": "ipv4 and ipv6"

**Comment by qdm12** [comment] 2024-04-16 14:47
Duplicate of #507 please subscribe to that one instead, thanks!

**Closed by qdm12** 2024-04-16 14:47 UTC
Labels: Closed: 👥 Duplicate
