### ISSUE TITLE
Add DNSExit.com as a provider

### ISSUE THREAD

**Issue by mr-orreo** [qdm12/ddns-updater#675] opened 2024-03-15 21:40 UTC
1. Add DNSExit.com as a provider.

2. In previous versions of TrueNAS Scale, Dynamic DNS was included under services, with an option to select DNSExit.com as a provider. This was deprecated in SCALE 23.10 and it's now recommended to use DDNS Updater instead, but the option to utilize DNSExit.com as a provider is unavailable.
3. References:
https://www.truenas.com/docs/scale/22.12/scaleuireference/systemsettings/services/ddnsservicescreenscale/
https://www.truenas.com/docs/scale/22.12/gettingstarted/scaledeprecatedfeatures/

**Comment by qdm12** [comment] 2024-03-16 06:46
Noted, and note you may be able to use the https://github.com/qdm12/ddns-updater/blob/master/docs/custom.md provider for the time being. Alternatively, there is a decent guide on how to contribute and add native support in the code, see the .github/CONTRIBUTING.md doc 😉

**Comment by qdm12** [comment] 2024-05-06 11:17
Duplicate of #346 I've added the details you gave and tagged you there. Please subscribe to #346 instead to be notified when this is done. Thanks!

**Closed by qdm12** 2024-05-06 11:17 UTC
Labels: Closed: 👥 Duplicate, Priority: 💤 Low priority, Category: New provider 🆕
