### ISSUE TITLE
Feature request: ...

### ISSUE THREAD

**Issue by Into69** [qdm12/ddns-updater#479] opened 2023-06-04 12:35 UTC
1. What's the feature?
Support for easydns

2. Extra information?
You can send the following parameters in the QUERY_STRING of a request, for example:

https://username:dynamictoken@api.cp.easydns.com/dyn/generic.php?hostname=example.com&myip=10.0.0.2

If you do not include the myip parameter, our update script will look to the IP the request originates from and update to that.

**Comment by qdm12** [comment] 2023-06-05 06:47
Duplicate of #421

**Closed by qdm12** 2023-06-05 06:47 UTC
Labels: :bulb: feature request
