### ISSUE TITLE
Bug: OVH ZoneDNS is not working

### ISSUE THREAD

**Issue by fallenczar** [qdm12/ddns-updater#204] opened 2021-05-18 06:58 UTC
**TLDR**: ZONEDNS information provided as per sample config.json, however logs show that the program is expecting "username" and "password"

1. Is this urgent: Yes
2. DNS provider(s) you use: OVH
3. Program version: commit 864a696

    

    `Running version latest built on 2020-03-13T01:30:06Z (commit d0f678c)`

4. What are you using to run the container: docker-compose
5. Extra information (optional)

Logs:

```log

```

Configuration file (**remove your credentials!**):

```json
{
  "settings": [
    {
      "provider": "ovh",
      "domain": "example.ovh",
      "host": "@",
      "username": "example.ovh-test", # added as per error log
      "password": "12345678", # added as per error log
      "api_endpoint": "ovh-eu",
      "app_key": "****",
      "app_secret": "****",
      "consumer_key": "****",
      "ip_version": "ipv4",
      "provider_ip": true
    }
  ]
}
```

Host OS:OMV - docker

**Comment by fredericrous** [comment] 2021-05-18 22:21
the example is not perfectly clear but the documentation is.
Basically either you use DynHost (aka `dynamic`) or ZoneDNS (aka `api`)

example for the zonedns mode:

```
        {
            "provider": "ovh",
            "domain": "myserver.tld",
            "host": "@",
            "mode": "api",
            "app_key": "some-api-key",
            "app_secret": "some-app-secret",
            "consumer_key": "some-consumer-key"
        }
```

**Comment by qdm12** [comment] 2021-06-07 16:13
Hey guys, I just pushed b8c97e78faf83695ad1088fa06ee2b7227e5a798 which removes the dependency on OVH's go library, can you try pulling `:latest` and see if it works using the zoneDNS (API)? If it doesn't work, I made a release image tag `v2.3.0` just before changing this, so you can use that to fallback. Thanks!

Also I'm updating the documentation now to close this issue.

**Comment by fredericrous** [comment] 2021-06-28 03:13
There is a regression. I'm getting ` 2021/06/28 02:32:46 ERROR /updater/data/updates.json validation error: IP 1 of 1 is empty for record {"domain":"daddyshome.fr","host":"@","ips":[{"ip":"","time":"2021-06-12T19:47:48.567727675Z"}]}`

**Comment by qdm12** [comment] 2021-06-28 15:51
Thanks for letting me know! Were these using the Zone API? The only line I see is [this one](https://github.com/qdm12/ddns-updater/blob/master/internal/settings/providers/ovh/provider.go#L231) where we return the IP address given to do the update as the new IP, so I don't really see why it would be set to an empty string, strange 🤔 I'll dig more later.

**Comment by fredericrous** [comment] 2021-07-08 07:22
yes, it was Zone API

```
{
    "settings": [
        {
            "provider": "ovh",
            "domain": "domain.tld",
            "host": "@",
            "mode": "api",
            "app_key": "XXX",
            "app_secret": "XXX",
            "consumer_key": "XXX"
        },
        {
            "provider": "ovh",
            "domain": "domain.tld",
            "host": "*",
            "mode": "api",
            "app_key": "XXX",
            "app_secret": "XXX",
            "consumer_key": "XXXX"
        },
    ]
}
```

**Comment by qdm12** [comment] 2022-01-21 13:45
Closing this due to inactivity. Feel free to comment if it's still unresolved.

**Closed by qdm12** 2022-01-21 13:45 UTC
Labels: :memo: documentation

**Comment by silkyclouds** [comment] 2023-03-14 10:58
hi gents, I've followed the link you provide to create an app + api keys. But I end up with this : 

<img width="528" alt="image" src="https://user-images.githubusercontent.com/23377067/224980523-e5597fbc-f6b7-4d42-8b02-b08258f0a9c1.png">

question is, where can I find my customer key ? 

thanks !
