### ISSUE TITLE
Feature request: add zoneedit.com

### ISSUE THREAD

**Issue by Robbocop1389** [qdm12/ddns-updater#311] opened 2022-02-19 14:45 UTC
**EDITED by @qdm12**

See https://kb.easydns.com/knowledge/dynamic-dns/ for details on easyDNS, and replace `api.cp.easydns.com` with `api.cp.zoneedit.com`

TLDR:

```
https://username:dynamictoken@api.cp.zoneedit.com/dyn/generic.php?hostname=example.com&myip=10.0.0.2
```

Note #421 should probably be done at the same time.

**Comment by qdm12** [comment] 2023-06-12 14:53
Duplicate of #226 

Please try image tag `:pr-482` and report if it works or not on #226 documentation is at https://github.com/qdm12/ddns-updater/blob/zoneedit/docs/zoneedit.md

**Closed by qdm12** 2023-06-12 14:53 UTC
Labels: 👥 Duplicate

**Comment by qdm12** [comment] 2023-06-14 07:04
Also FYI zoneedit.com was definitely NOT a clone of easydns, all its responses are different, and also their documentation is non-existant regarding their API responses... also they require a 10min period between update... so yes very very different 😉
