### ISSUE TITLE
Support for ipv64.net

### ISSUE THREAD

**Issue by Kritz0** [qdm12/ddns-updater#840] opened 2024-10-13 14:30 UTC
1. What's the feature? A free ddns service (https://ipv64.net)

3. Extra information? https://ipv64.net/dyndns_helper.php?

**Comment by bentemple** [comment] 2024-10-23 14:53
I can look into adding this.
API Docs: https://ipv64.net/dyndns_updater_api
Seems like they have a fully functioning API which allows for querying for current DNS entries etc...


I believe you may be able to use a [custom](https://github.com/qdm12/ddns-updater/blob/master/docs/custom.md) configuration to do this already.
DDNS-Updater config would look something like this, where `YOUR_API_KEY` is changed to your ipv64.net api key and `YOUR_DOMAIN.ipv64.net` is changed to your domain name.
NOTE: Change `ip_version` to `ipv6` if you're using ipv6:

```
{
  "settings": [
    {
      "provider": "custom",
      "domain": "example.ipv64.net",
      "url": "https://ipv64.net/update.php?key=YOUR_API_KEY&domain=example.ipv64.net"
      "ipv4key": "ip",
      "ipv6key": "ip6",
      "success_regex": "success",
      "ip_version": "ipv4"
    }
  ]
}
```

**Comment by qdm12** [comment] 2024-10-23 14:55
@bentemple please go ahead if you feel like it 😉
Also that comment on the custom provider is definitely something I'll re-use for other issues 😄 !

**Comment by bentemple** [comment] 2024-10-23 15:02
Heh, just scrolling through the issues trying to triage. Figured a bunch of these could get knocked out with the pre-existing custom feature since most are simple http requests.

I started at the top, but then realized, there are so many domain provider requests, probably makes more sense to start at the oldest and work my way forward prioritizing the ones with the most comments / upvotes.

**Comment by qdm12** [comment] 2024-11-19 12:24
Duplicate of #511 so moving essential bits from here to there;
It might be worth investigating a way to easily add these 'dumb ddns' registrars easily in code, for example add a single line to a `map[string]string` of name to update url, and use the 'custom' provider code 🤔 Something like that would be nice to accelerate resolving requests for registrars. Maybe even a little separate CLI tool `cmd/new-provider/main.go` to add the new provider to the readme, create a docs/newprovider.md and add it to the Go code where necessary. Anyway, one can dream 😄

**Closed by qdm12** 2024-11-19 12:24 UTC
Labels: Category: New provider 🆕
