### ISSUE TITLE
Feature request: Support for ClouDNS

### ISSUE THREAD

**Issue by Sophist-UK** [qdm12/ddns-updater#665] opened 2024-03-06 17:18 UTC
Support ClouDNS - https://www.cloudns.net/wiki/

**Comment by qdm12** [comment] 2024-03-07 10:58
Duplicate of #455 please subscribe to this one instead, thanks!

**Closed by qdm12** 2024-03-07 10:58 UTC
Labels: Closed: 👥 Duplicate

**Comment by Sophist-UK** [comment] 2024-03-07 11:33
Apologies for not spotting that.
